### ISSUE TITLE
Can’t run

### ISSUE THREAD

**Issue by enrixp** [smartperson/spartan-edge-accelerator-graphical-system#1]
The project can’t run on my Vivado 2019 
Some drive letters are not correct 
And hex file missing .
Can you post the bitstream as well 
Thanks 
Regards

**Comment by smartperson** [comment]
Thanks for the report! Do you have any logs you can attach? The .hex file is included, but I wonder if the path is absolute instead of relative.

**Comment by enrixp** [comment]
Initially once open the project file is read only .
Secondly the drive paths are not on the directory 
Third the hex file is not available 
I’ll get a screen shot later for you

**Comment by enrixp** [comment]
![image](https://user-images.githubusercontent.com/36482602/85047055-e65fd280-b1c3-11ea-9545-aa09e4276003.png)

**Comment by enrixp** [comment]
![image](https://user-images.githubusercontent.com/36482602/85047340-3f2f6b00-b1c4-11ea-8898-132da3394515.png)

**Comment by smartperson** [comment]
That's helpful, thanks. I've tried changing the hex file's settings in the project to use a relative path. I'm setting up a clean windows VM to test it and see if it will work before committing. I'll keep you updated.

**Comment by enrixp** [comment]
Thank you so much

**Comment by enrixp** [comment]
I’ll try it today and see if it works

**Comment by enrixp** [comment]
So I managed to display on the HDMI screen .
Awesome

**Comment by enrixp** [comment]
![Uploading 85101104...]()

**Comment by enrixp** [comment]
It Mario is not running around 🥱

**Comment by enrixp** [comment]
the code is good .
just need to make the mario runing .
it runs once you reset the esp32 so have to figure that out .

**Comment by smartperson** [comment]
Great! I'll still check on my VM and figure out how to get the project to be machine independent.
For getting Mario to move around, there's a line in the sprite compositor right now that checks on FPGA pin B12, or ESP32 GPIO27, and only moves Mario when that signal is asserted. You can either comment out that code or write a program for the ESP32 that sets the signal to HIGH.

I probably should have worked on that on a separate branch.

**Comment by enrixp** [comment]
Cool let me try that .

**Comment by smartperson** [comment]
Thanks again. I think I found all of the issues with external file references and intermediate build products. I've linked the pull request I've made thanks to your efforts!

**Comment by enrixp** [comment]
I have tried it today it works fine perfectly great work .
![Uploading 86514521...]()
